config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "chats#index"
  resources :chats, only: [:index, :create]
  resources :groups, only: [:new, :create, :edit, :update, :show] do
    collection do
      get 'search'
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_users
  has_many :users, through: :group_users
  has_many :messages

  validates :name, presence: true

  attr_accessor :user

  def member_names
    users_names = users.map(&:name)
    return "Members: #{users_names.join(" ")}"
  end
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :group

  validates :body, presence: true
  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :messages
  has_many :group_users
  has_many :groups, through: :group_users

  validates :name, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  # before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_in, keys:[:name])
    devise_parameter_sanitizer.permit(:sign_up, keys:[:name])
  end
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  def index
    @message = Message.new
    @groups = current_user.groups
  end

  def create
    @message = Message.new(create_params)
    @group = @message.group
    if @message.save
      respond_to do |format|
        format.html { redirect_to group_path(@group) }
        format.json { render json: { body: @message.body, user_name: @message.user.name, created_at: @message.created_at, image: @message.image_url}}
      end
    else
      flash[:alert] = "メッセージを入力してください"
      redirect_to group_path(@group)
    end
  end

  private
  def create_params
      params.require(:message).permit(:body, :group_id, :image).merge(user_id: current_user.id)
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group ,only: [:edit, :update, :show]

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(create_params)
    if @group.save
      flash[:notice] = "チャットグループが作成されました"
      redirect_to group_path(@group)
    else
      flash[:alert] = @group.errors.full_messages
      flash[:alert_length] = "#{flash[:alert].length} error prohibited this chat_group from being saved:"
      redirect_to new_group_path
    end
  end

  def edit
    @users = @group.users
  end

  def update
    if @group.update(create_params)
      flash[:notice] = "チャットグループが更新されました"
      redirect_to group_path(@group)
    else
      flash[:alert] = @group.errors.full_messages
      flash[:alert_length] = "#{flash[:alert].length} error prohibited this chat_group from being saved:"
      redirect_to edit_group_path
    end
  end

  def show
    if @group.users.include?(current_user)
      @groups = current_user.groups.all
      @messages = @group.messages
      @message = Message.new
      respond_to do |format|
        format.html
        format.json { render json: { messages: @messages, users: @messages.map{|message| message.user}, current_user: current_user}}
      end
    else
      redirect_to root_path
      flash[:alert] = "このグループに所属していません"
    end
  end

  def search
    if params.present?
      @users = User.where("name LIKE?", "%#{params.require(:user)[:name]}%")
    end
    respond_to do |format|
      format.html { redirect_to root_path}
      format.json { render json: { users: @users}}
    end
  end

  private
  def create_params
    params.require(:chat_group).permit(:name, {user_ids: []})
  end

  def set_group
    @group = Group.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/chats/index.html.haml
- if flash[:notice].present?
  .layout-notice
    =flash[:notice]

- if flash[:alert].present?
  .error_message
    =flash[:alert]

.chat
  .chat__side
    .chat__side--user
      %h5= current_user.name
      = link_to edit_user_registration_path, class: "edit-user-registration" do
        %i.fa.fa-cog
      = link_to new_group_path, class: "create-a-chat-group" do
        %i.fa.fa-pencil-square-o
    %ul.chat__side--groups
      - @groups.each do |group|
        %li.chat__side--group
          = link_to group_path(group), class: "chat--group__link" do
            %p.chat--group__name= group.name
            -if group.messages.present?
              %p.chat--group__message= group.messages.first.body

app/views/groups/edit.html.haml
.chat-group-form
  %h1 チャットグループ編集
  = form_for @group do |f|
    - if flash[:alert]
      .chat-group-form__errors
        %h2= flash[:alert_length]
        %ul
          - flash[:alert].each do |alert|
            %li= alert
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
        = f.label :name, "グループ名", class: 'chat-group-form__label', for: 'chat_group_name'
      .chat-group-form__field--right
        = f.text_field :name, class: 'chat-group-form__input', id: 'chat_group_name', placeholder: "グループ名を入力してください", :name => "chat_group[name]",value: @group.name
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
        = f.label :users, "チャットメンバーを追加", class: 'chat-group-form__label'
    .chat-group-form__field--right
      .chat-group-form__search.clearfix
        = collection_check_boxes(:chat_group, :user_ids, User.all, :id, :name) do |b|
          = b.label { b.check_box + b.text }
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
        .chat-group-form__label チャットメンバー
      - @users.each do |user|
        .chat-group-form__field--right
          #chat-group-users
            .chat-group-user.clearfix
              = user.name

    .chat-group-form__field.clearfix
      .chat-group-form__field--left
      .chat-group-form__field--right
        = f.submit class:'chat-group-form__action-btn', value:"Submit"

app/views/groups/new.html.haml
.chat-group-form
  %h1 新規チャットグループ
  = form_for @group do |f|
    - if flash[:alert]
      .chat-group-form__errors
        %h2= flash[:alert_length]
        %ul
          - flash[:alert].each do |alert|
            %li= alert
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
        = f.label :name, "グループ名", class: 'chat-group-form__label', for: 'chat_group_name'
      .chat-group-form__field--right
        = f.text_field :name, class: 'chat-group-form__input', id: 'chat_group_name', placeholder: "グループ名を入力してください", name: "chat_group[name]"
    .chat-group-form__field.clearfix#user_field
      .chat-group-form__field--left
        = f.label :user, "チャットメンバーを追加", class: 'chat-group-form__label'
      .chat-group-form__field--right
        = f.text_field :user, class: 'chat-group-form__input', id: 'chat_user_name', placeholder: "追加したいユーザー名を入力してください", name: "chat_group[user_name]"
      #chat-user-result

    .chat-group-form__field.clearfix
      .chat-group-form__field--left
        .chat-group-form__label チャットメンバー
      .chat-group-form__field--right
        #chat-group-users
          #chat-group-user.chat-group-user.clearfix
            = current_user.name

    .chat-group-form__field.clearfix
      .chat-group-form__field--left
      .chat-group-form__field--right
        = f.submit class:'chat-group-form__action-btn', value:"Submit"

app/views/groups/show.html.haml
- if flash[:notice].present?
  .layout-notice
    =flash[:notice]

- if flash[:alert].present?
  .error_message
    =flash[:alert]

.chat
  .chat__side
    .chat__side--user
      %h5= current_user.name
      = link_to edit_user_registration_path, class: "edit-user-registration" do
        %i.fa.fa-cog
      = link_to new_group_path, class: "create-a-chat-group" do
        %i.fa.fa-pencil-square-o
    %ul.chat__side--groups
      - @groups.each do |group|
        %li.chat__side--group
          = link_to group_path(group), class: "chat--group__link" do
            %p.chat--group__name= group.name
            -if group.messages.present?
              %p.chat--group__message= group.messages[0].body

  .chat__main
    .chat__main--header
      .chat__main--header__left
        %h2= @group.name
        %p= @group.member_names
      .chat__main--header__right
        = link_to "Edit", edit_group_path(@group)
    .chat__main--body
      %ul.chat__main--body--list
        -@messages.each do |message|
          %li
            .chat__main--body--block
              .chat__main--body--block--name= message.user.name
              .chat__main--body--block--date= message.created_at
            %p.chat__main--body--message= message.body
            = image_tag message.image

    .chat__main--footer
      = form_for @message, url: chats_path, method: :post do |f|
        = f.hidden_field :group_id, value: @group.id
        .chat__main--footer--block__left
          = f.text_area :body, id:"chat__main--footer--text-js", placeholder: "type a message"
        .chat__main--footer--image
          = f.label :image, for: 'image-upload' do
            %i.fa.fa-image
            = f.file_field :image, id: 'image-upload',style: "display:none;"
        = f.submit class:"chat__main--footer--block__right", value: "Submit"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Chatspace
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = yield